export const enum Controls {
  ShowSuggest,
  WorkbenchCssPath,
  Gradient,
  GradientBrightness,
  GradientDarkness,
  HashSource,
  Refresh,
  RandomColor,
  'RandomColor.colorSet',
  'RandomColor.pure',
  'RandomColor.specify',
  ProjectIndicators,
  ThemeColors,
  'ThemeColors.light',
  'ThemeColors.dark',
}
